name: Cypress

on:
  push:
    branches:
      - never

jobs:
  build-and-publish-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 16          
      - uses: azure/docker-login@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the project
        run: |
          npm ci
          npm run clean
          npm run build
      - name: Build Docker image
        run: docker build --tag ${{ github.repository }}:ci_${{ github.sha }} .
      - name: Publish to DockerHub
        run: docker push ${{ github.repository }}:ci_${{ github.sha }}

  e2e-cypress-service-test:
    name: Setup staging frontend and test end to end
    needs: [build-and-publish-ci]
    runs-on: ubuntu-latest
    services:
      frontend-service:
        image: ${{ github.repository }}:ci_${{ github.sha }}
        env:
          EDU_SHARING_API_URL: https://redaktion-staging.openeduhub.net/edu-sharing/rest
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_baseUrl: http://localhost:8080
        with:
          working-directory: e2e-cypress
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e-cypress/cypress/screenshots
