name: Docker-CI

on:
  pull_request:
    branches: [ develop, master]

jobs:
  build-and-publish-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the project
      run: |
        npm ci
        npm run clean
        npm run build:stage
    - name: Build Docker image
      run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $VERSION
#      run: docker build --tag openeduhub/frontend .
#    - name: Publish to DockerHub
#      run: docker push openeduhub/frontend

