name: Lint

on:
  push:
    branches:
      - never

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # `npm run lint` will fail for node <= 14 (probably due to npm < 7).
      - uses: actions/setup-node@v2
        with:
          node-version: '16'    
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
