name: CI

on:
  pull_request:
    branches: [ develop, master]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  e2e-cypress:
    runs-on: ubuntu-20.04
    name: Setup staging frontend and test end to end
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: Install dependencies
        run: npm install
      - name: build stage sources
        run: npm run build:stage
