name: CI

on:
  push:
    branches: [ develop, master]
  pull_request:
    branches: [ develop, master]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: use node.js 12.16
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: install dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  build-and-publish-ci:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the project
        run: |
          npm ci
          npm run clean
          npm run build:stage
      - name: Build Docker image
        run: docker build --tag openeduhub/frontend:ci_${GITHUB_SHA} .
      - name: Publish to DockerHub
        run: docker push openeduhub/frontend:ci_${GITHUB_SHA}

  e2e-cypress:
    needs: [lint, build-and-publish-ci]
    container:
      image: openeduhub/frontend:ci_${{ github.sha }}
      ports:
        - 8000
    runs-on: ubuntu-18.04
    name: setup staging frontend and test end to end
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use node.js 12.16
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: cypress run
        env:
            CYPRESS_baseUrl: http://localhost:8000
        uses: cypress-io/github-action@v2
        with:
            working-directory: e2e-cypress

